#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Carles Ortega Ragull (ragull, socat, carles) <ragull@socket.cat>
#
# Installs a plain-bash pre-commit hook that runs scripts/check-agpl-header.sh.
# No husky / node required. Safe to re-run (overwrites in place).
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
HOOKS="$ROOT/.git/hooks"
mkdir -p "$HOOKS"

cat > "$HOOKS/pre-commit" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit by hand.
exec bash "$(git rev-parse --show-toplevel)/scripts/check-agpl-header.sh"
EOF
chmod +x "$HOOKS/pre-commit"

echo "Installed: .git/hooks/pre-commit (AGPL-3.0 header check)"
